### ISSUE TITLE
Error: Cannot find module './SH1107.js'

### ISSUE THREAD

**Issue by node-joe** [Lyubomir-Todorov/node-red-contrib-sgp30#1]
Error is below...  Looks like it is requiring additional modules, not even seeing how to add them.  Just looking to use the Node as standalone Node on a raspberry pi for to get the readings, without any additional OLEDs...

-Joe

Error: Cannot find module './SH1107.js'
Require stack:
- /root/.node-red/node_modules/node-red-contrib-sgp30/BreakoutGardener/modules/SGP30.js
- /root/.node-red/node_modules/node-red-contrib-sgp30/sgp30.js
- /usr/lib/node_modules/node-red/node_modules/@node-red/registry/lib/loader.js
- /usr/lib/node_modules/node-red/node_modules/@node-red/registry/lib/index.js
- /usr/lib/node_modules/node-red/node_modules/@node-red/runtime/lib/nodes/index.js
- /usr/lib/node_modules/node-red/node_modules/@node-red/runtime/lib/index.js
- /usr/lib/node_modules/node-red/lib/red.js
- /usr/lib/node_modules/node-red/red.js

**Comment by node-joe** [comment]
For my use as work around, I was able to comment out the required other modules at the beginning of SGP30.js to get it to work... Seems to work so far?  I wonder if it would be a good idea to create a bare bones Node for just this sensor?

const i2c = require('i2c-bus'); // -> https://github.com/fivdi/i2c-bus
//const SH1107 = require('./SH1107.js');
//const IS31FL3731_RGB = require('./IS31FL3731_RGB.js');
//const IS31FL3731_WHITE = require('./IS31FL3731_WHITE.js');
//const HT16K33 = require('./HT16K33.js');
//const DRV2605 = require('./DRV2605.js');

**Comment by Lyubomir-Todorov** [comment]
Hey there, thanks for letting me know about this issue. 
 
This was caused by the repository that interfaced with the sgp30 sensor. I've replaced it with a modified version that doesn't include any of these extra dependencies. I've tested it on my own Node-RED and its working fine now, let me know if you're still running into any issues with the updated node.

Cheers,
Leo

**Comment by node-joe** [comment]
Awesome, and thank you!  I'll test when I am back at work on Tuesday, I'll be installing a sensor fresh there.  I'll give it a test then at the lastest, I'll close out if I get a chance to test at home at home first.  Thanks again!

**Comment by node-joe** [comment]
All working!
